name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Install pnpm first
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          # set to the pnpm major you use locally (or omit if package.json has "packageManager")
          version: 9
          run_install: false

      # 2) Then setup Node with pnpm caching
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      # 3) Install deps & build
      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      # SPA fallback for GitHub Pages
      - name: Add 404 fallback
        run: cp dist/index.html dist/404.html

      # Upload built site for Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
